This document updates RESTCONF ^RFC8040^ in order to support the
Network Management Datastore Architecture (NMDA) defined in
^I-D.ietf-netmod-revised-datastores^.

* Introduction

This document updates RESTCONF ^RFC8040^ in order to support the
Network Management Datastore Architecture (NMDA) defined in
^I-D.ietf-netmod-revised-datastores^.

The solution presented in this document is backwards compatible with
^RFC8040^.  This is achieved by it only adding new top-level
resources, and thereby leaving the semantics of all existing
resources alone.

** Terminology

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
"OPTIONAL" in this document are to be interpreted as described in BCP
14 ^RFC2119^ ^RFC8174^ when, and only when, they appear in all
capitals, as shown here.

The following terms are defined in
^I-D.ietf-netmod-revised-datastores^ and are not redefined here:

- operational state datastore
- running configuration datastore
- intended configuration datastore

* Summary of Updates to RFC 8040

This document updates ^RFC8040^ in the following ways:

- Adds new top-level resource "/ds".
- Adds new query parameter "with-origin".
- Section 3.5.4, Paragraph 3 in ^RFC8040^ doesn't apply when
  interacting with any resource under {+restconf}/ds.
- Updates section 10 in ^RFC8040^ by requiring servers that support NMDA to
  implement "ietf-yang-library" as defined in
  ^I-D.nmdsdt-netconf-rfc7895bis^.

* Conformance

RFC Ed.: Update 201X-XX-XX below with correct date.

An NMDA-compliant RESTCONF server MUST support the operational state
datastore.  Such a server identifies that it supports NMDA both by
implementing the {+restconf}/ds/ietf-datastores:operational resource,
and by implementing at least revision 201X-XX-XX of the
"ietf-yang-library" module, as specified in
^I-D.nmdsdt-netconf-rfc7895bis^.

A RESTCONF client can test if a server supports the NMDA by using
either the HEAD or GET methods on
{+restconf}/ds/ietf-datastores:operational.

* The {+restconf}/ds/<datastore> Resources

This document defines a set of new resources representing datastores
as defined in ^I-D.ietf-netmod-revised-datastores^.  These
resources are available using the resource path template:

  {+restconf}/ds/<datastore>

Where <datastore> is encoded as an "identity" according to the JSON
encoding rules for identities, defined in Section 4 of ^RFC7951^.
Such an identity MUST be derived from the "datastore" identity in
"ietf-datastores" ^I-D.ietf-netmod-revised-datastores^.

Specifically:

- The resource {+restconf}/ds/ietf-datastores:operational
  refers to the operational state datastore.
- The resource {+restconf}/ds/ietf-datastores:running refers to the
  running configuration datastore.
- The resource {+restconf}/ds/ietf-datastores:intended refers to the
  intended configuration datastore.

An NMDA-compliant server MUST implement
{+restconf}/ds/ietf-datastores:operational.  Other datastore resources
are optional to implement.

YANG actions can only be invoked in
{+restconf}/ds/ietf-datastores:operational.

If a server implements the example datastore "ds-ephemeral" in
the module "example-ds-ephemeral", it would implement the resource
{+restconf}/ds/example-ds-ephemeral:ds-ephemeral.

* Protocol Operations

All existing protocol operations defined in ^RFC8040^ for the
{+restconf}/data resource are available for all of the new datastore
resources with the following exceptions:

- Dynamic datastores are excluded, as each dynamic datastore
  definition needs to be reviewed for what protocol operations it
  supports.

- Some datastores are read-only by nature (e.g., <intended>), and
  hence any attempt to modify these datastores will fail.

- The "with-defaults" query parameter (^RFC8040^, Section 4.8.9) does
  not apply when interacting with
  {+restconf}/ds/ietf-datastores:operational.  This means that all
  values are always returned from the operational state datastore,
  even if a node happens to have a default statement in the YANG
  module, and this default value is being used by the server. If the
  "with-defaults" query parameter is present in a request to this
  resource, the server MUST return a response with a "400 Bad Request"
  status-line.  The error-tag value "invalid-value" is used in this
  case.

- ^RFC8040^, section 3.5.4, paragraph 3 does not apply when
  interacting with any resource under {+restconf}/ds.

** The "with-origin" query parameter

The GET operation adds a new query parameter named "with-origin",
which if present, requests that the server includes "origin" metadata
anotations in its response, as detailed in the NMDA.  This parameter
is only valid when querying {+restconf}/ds/ietf-datastores:operational
or any datastores with identities derived from the "operational"
identity. Otherwise, if an invalid datastore is specified then the
server MUST return a response witha a "400 Bad Request" status-line,
using an error-tag value of "invalid-value".  "origin" metadata
annotations are not included unless a client explicitly requests them.

Data from <operational> can come from multiple sources.  The server
should return the most accurate value for the "origin" metadata
annotation as possible, indicating the source of the operational value,
as specified in section 5.3.4 of the NMDA.

When encoding the origin metadata annotation for a hierarchy of
returned nodes, the annotation may be omitted for a child node when
the value matches that of the parent node (as described in
ietf-origin@2017-08-17). [RFC Editor, please check published revision
date.]

The "with-origin" query parameter is optional to support.  It is
identified with the URI:

  urn:ietf:params:restconf:capability:with-origin:1.0

* Security Considerations

TBD

* IANA Considerations

This document defines one capability in the "RESTCONF Capability URNs"
registry defined in ^RFC8040^:

  Index          Capability Identifier
  ------------------------------------------------------------------

  :with-origin   urn:ietf:params:restconf:capability:with-origin:1.0

*! start-appendix

* Example

TBD



{{document:
    name ;
    ipr trust200902;
    category std;
    references references.xml;
    updates 8040;
    title "RESTCONF Update to Support the NMDA";
    contributor "author:Martin Bjorklund:Tail-f Systems:mbj@tail-f.com";
    contributor "author:Juergen Schoenwaelder:Jacobs University:j.schoenwaelder@jacobs-university.de";
    contributor "author:Phil Shafer:Juniper Networks:phil@juniper.net";
    contributor "author:Kent Watsen:Juniper Networks:kwatsen@juniper.net";
    contributor "author:Robert Wilton:Cisco Systems:rwilton@cisco.com";
}}

